"""add_past_leadership_recognition_tables

Revision ID: 000ee02cd3df
Revises: 9c1f4d2b8a65
Create Date: 2026-07-23 06:30:22.650969

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000ee02cd3df'
down_revision: str | Sequence[str] | None = '9c1f4d2b8a65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'cms_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    )
    op.create_index('ix_cms_pages_slug', 'cms_pages', ['slug'], unique=True)
    op.create_index('ix_cms_pages_is_published', 'cms_pages', ['is_published'], unique=False)
    op.create_index(
        'uq_leadership_terms_current',
        'leadership_terms',
        ['is_current'],
        unique=True,
        postgresql_where=sa.text("is_current = true AND deleted_at IS NULL"),
    )
    op.create_index(
        'uq_leadership_terms_active_academic_year',
        'leadership_terms',
        ['academic_year'],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table('leadership_administrations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('slogan', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.Date(), nullable=True),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('group_photo_key', sa.String(length=1000), nullable=True),
    sa.Column('group_photo_url', sa.String(length=1000), nullable=True),
    sa.Column('group_photo_alt', sa.String(length=500), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('executive_count', sa.Integer(), nullable=False),
    sa.Column('committee_count', sa.Integer(), nullable=False),
    sa.Column('initiatives_count', sa.Integer(), nullable=False),
    sa.Column('lives_impacted', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['leadership_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id')
    )
    op.create_index('ix_leadership_administrations_term_id', 'leadership_administrations', ['term_id'], unique=True)
    op.create_index(op.f('ix_leadership_administrations_academic_year'), 'leadership_administrations', ['academic_year'], unique=True)
    op.create_index(op.f('ix_leadership_administrations_display_order'), 'leadership_administrations', ['display_order'], unique=False)
    op.create_index(op.f('ix_leadership_administrations_is_current'), 'leadership_administrations', ['is_current'], unique=False)
    op.create_index(op.f('ix_leadership_administrations_slug'), 'leadership_administrations', ['slug'], unique=True)
    op.create_index(op.f('ix_leadership_administrations_status'), 'leadership_administrations', ['status'], unique=False)
    op.create_table('leadership_timeline_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('year_label', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leadership_timeline_events_display_order'), 'leadership_timeline_events', ['display_order'], unique=False)
    op.create_index(op.f('ix_leadership_timeline_events_status'), 'leadership_timeline_events', ['status'], unique=False)
    op.create_index(op.f('ix_leadership_timeline_events_year_label'), 'leadership_timeline_events', ['year_label'], unique=False)
    op.create_table('legacy_awards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('award_year', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('image_key', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_alt', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_awards_award_year'), 'legacy_awards', ['award_year'], unique=False)
    op.create_index(op.f('ix_legacy_awards_display_order'), 'legacy_awards', ['display_order'], unique=False)
    op.create_index(op.f('ix_legacy_awards_is_featured'), 'legacy_awards', ['is_featured'], unique=False)
    op.create_index(op.f('ix_legacy_awards_slug'), 'legacy_awards', ['slug'], unique=True)
    op.create_index(op.f('ix_legacy_awards_status'), 'legacy_awards', ['status'], unique=False)
    op.create_table('recognition_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_recognition_categories_display_order'), 'recognition_categories', ['display_order'], unique=False)
    op.create_index(op.f('ix_recognition_categories_slug'), 'recognition_categories', ['slug'], unique=True)
    op.create_index(op.f('ix_recognition_categories_status'), 'recognition_categories', ['status'], unique=False)
    op.create_table('administration_achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('administration_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('year_label', sa.String(length=20), nullable=True),
    sa.Column('image_key', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_alt', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['administration_id'], ['leadership_administrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administration_achievements_administration_id'), 'administration_achievements', ['administration_id'], unique=False)
    op.create_index(op.f('ix_administration_achievements_status'), 'administration_achievements', ['status'], unique=False)
    op.create_table('historical_record_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=False),
    sa.Column('submitter_phone', sa.String(length=50), nullable=True),
    sa.Column('relationship_to_gpsa', sa.String(length=100), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('administration_year', sa.String(length=20), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('file_key', sa.String(length=1000), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('consent_to_archive', sa.Boolean(), nullable=False),
    sa.Column('consent_to_publish', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_record_submissions_status'), 'historical_record_submissions', ['status'], unique=False)
    op.create_table('leader_nominations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nominee_name', sa.String(length=255), nullable=False),
    sa.Column('nominee_email', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('administration_year', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('evidence_file_key', sa.String(length=1000), nullable=True),
    sa.Column('evidence_file_url', sa.String(length=1000), nullable=True),
    sa.Column('nominator_name', sa.String(length=255), nullable=False),
    sa.Column('nominator_email', sa.String(length=255), nullable=False),
    sa.Column('relationship_to_nominee', sa.String(length=100), nullable=True),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['recognition_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leader_nominations_status'), 'leader_nominations', ['status'], unique=False)
    op.create_table('recognition_honourees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.Column('full_name_override', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('recognition_year', sa.String(length=20), nullable=True),
    sa.Column('class_year', sa.String(length=50), nullable=True),
    sa.Column('photo_key', sa.String(length=1000), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('photo_alt', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['recognition_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_id'], ['leaders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognition_honourees_category_id'), 'recognition_honourees', ['category_id'], unique=False)
    op.create_index(op.f('ix_recognition_honourees_leader_id'), 'recognition_honourees', ['leader_id'], unique=False)
    op.create_index(op.f('ix_recognition_honourees_status'), 'recognition_honourees', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_honourees_status'), table_name='recognition_honourees')
    op.drop_index(op.f('ix_recognition_honourees_leader_id'), table_name='recognition_honourees')
    op.drop_index(op.f('ix_recognition_honourees_category_id'), table_name='recognition_honourees')
    op.drop_table('recognition_honourees')
    op.drop_index(op.f('ix_leader_nominations_status'), table_name='leader_nominations')
    op.drop_table('leader_nominations')
    op.drop_index(op.f('ix_historical_record_submissions_status'), table_name='historical_record_submissions')
    op.drop_table('historical_record_submissions')
    op.drop_index(op.f('ix_administration_achievements_status'), table_name='administration_achievements')
    op.drop_index(op.f('ix_administration_achievements_administration_id'), table_name='administration_achievements')
    op.drop_table('administration_achievements')
    op.drop_index(op.f('ix_recognition_categories_status'), table_name='recognition_categories')
    op.drop_index(op.f('ix_recognition_categories_slug'), table_name='recognition_categories')
    op.drop_index(op.f('ix_recognition_categories_display_order'), table_name='recognition_categories')
    op.drop_table('recognition_categories')
    op.drop_index(op.f('ix_legacy_awards_status'), table_name='legacy_awards')
    op.drop_index(op.f('ix_legacy_awards_slug'), table_name='legacy_awards')
    op.drop_index(op.f('ix_legacy_awards_is_featured'), table_name='legacy_awards')
    op.drop_index(op.f('ix_legacy_awards_display_order'), table_name='legacy_awards')
    op.drop_index(op.f('ix_legacy_awards_award_year'), table_name='legacy_awards')
    op.drop_table('legacy_awards')
    op.drop_index(op.f('ix_leadership_timeline_events_year_label'), table_name='leadership_timeline_events')
    op.drop_index(op.f('ix_leadership_timeline_events_status'), table_name='leadership_timeline_events')
    op.drop_index(op.f('ix_leadership_timeline_events_display_order'), table_name='leadership_timeline_events')
    op.drop_table('leadership_timeline_events')
    op.drop_index(op.f('ix_leadership_administrations_status'), table_name='leadership_administrations')
    op.drop_index(op.f('ix_leadership_administrations_slug'), table_name='leadership_administrations')
    op.drop_index(op.f('ix_leadership_administrations_is_current'), table_name='leadership_administrations')
    op.drop_index(op.f('ix_leadership_administrations_display_order'), table_name='leadership_administrations')
    op.drop_index(op.f('ix_leadership_administrations_academic_year'), table_name='leadership_administrations')
    op.drop_index('ix_leadership_administrations_term_id', table_name='leadership_administrations')
    op.drop_table('leadership_administrations')
    op.drop_index('ix_cms_pages_is_published', table_name='cms_pages')
    op.drop_index('ix_cms_pages_slug', table_name='cms_pages')
    op.drop_table('cms_pages')
    # ### end Alembic commands ###
    op.drop_index('uq_leadership_terms_active_academic_year', table_name='leadership_terms')
    op.drop_index('uq_leadership_terms_current', table_name='leadership_terms')
