"""improve_db_design

Revision ID: 388df832a17c
Revises: f97c30823c57
Create Date: 2026-07-13 12:59:56.145980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "388df832a17c"
down_revision: str | Sequence[str] | None = "f97c30823c57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "academic_resources",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.create_index(
        "ix_academic_resources_course_level_trimester",
        "academic_resources",
        ["course_id", "level", "trimester"],
        unique=False,
    )
    op.create_check_constraint("ck_courses_level_range", "courses", "level >= 100 AND level <= 600")
    op.create_check_constraint(
        "ck_users_level_range", "users", "level IS NULL OR (level >= 100 AND level <= 600)"
    )
    op.alter_column(
        "audit_logs",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "certificates",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "email_logs",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.create_index(
        "ix_email_logs_status_created", "email_logs", ["status", "created_at"], unique=False
    )
    op.alter_column(
        "event_registrations",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "event_registrations",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_event_registrations_event_id"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_user_id"), table_name="event_registrations")
    op.create_index(
        "ix_event_registrations_active_unique",
        "event_registrations",
        ["event_id", "user_id"],
        unique=True,
        postgresql_where="user_id IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_index(
        "ix_event_registrations_event_user",
        "event_registrations",
        ["event_id", "user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("event_registrations_event_id_fkey"), "event_registrations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "event_registrations", "events", ["event_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "events",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_events_start_datetime"), table_name="events")
    op.create_index("ix_events_status_start", "events", ["status", "start_datetime"], unique=False)
    op.alter_column(
        "feedback",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.create_index("ix_feedback_entity", "feedback", ["entity_type", "entity_id"], unique=False)
    op.alter_column(
        "news_posts",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.create_index(
        "ix_notifications_user_read_created",
        "notifications",
        ["user_id", "is_read", "created_at"],
        unique=False,
    )
    op.alter_column(
        "opportunities",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.create_index(
        "ix_opportunities_active_deadline", "opportunities", ["is_active", "deadline"], unique=False
    )
    op.alter_column(
        "password_reset_tokens",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "refresh_tokens",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "welfare_reports",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "welfare_reports",
        "submitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "welfare_spotlight",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "welfare_spotlight",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "welfare_reports",
        "submitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "welfare_reports",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "refresh_tokens",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_opportunities_active_deadline", table_name="opportunities")
    op.alter_column(
        "opportunities", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_index("ix_notifications_user_read_created", table_name="notifications")
    op.alter_column(
        "notifications", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "news_posts", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_index("ix_feedback_entity", table_name="feedback")
    op.alter_column(
        "feedback", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_index("ix_events_status_start", table_name="events")
    op.create_index(op.f("ix_events_start_datetime"), "events", ["start_datetime"], unique=False)
    op.alter_column(
        "events", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_constraint(None, "event_registrations", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_registrations_event_id_fkey"),
        "event_registrations",
        "events",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_event_registrations_event_user", table_name="event_registrations")
    op.drop_index(
        "ix_event_registrations_active_unique",
        table_name="event_registrations",
        postgresql_where="user_id IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_index(
        op.f("ix_event_registrations_user_id"), "event_registrations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_registrations_event_id"), "event_registrations", ["event_id"], unique=False
    )
    op.alter_column(
        "event_registrations",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "event_registrations",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_email_logs_status_created", table_name="email_logs")
    op.alter_column(
        "email_logs", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "courses", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "certificates", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "audit_logs", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.drop_index("ix_academic_resources_course_level_trimester", table_name="academic_resources")
    op.drop_constraint("ck_users_level_range", "users", type_="check")
    op.drop_constraint("ck_courses_level_range", "courses", type_="check")
    op.alter_column(
        "academic_resources",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
