"""add_html_body_to_email_logs

Revision ID: 5626195f3bd9
Revises: d69958028f74
Create Date: 2026-07-13 21:24:42.999075

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5626195f3bd9'
down_revision: str | Sequence[str] | None = 'd69958028f74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('html_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_logs', 'html_body')
    # ### end Alembic commands ###
