"""fix_fk_cascades_remove_redundant_feedback_fks

Revision ID: d69958028f74
Revises: 388df832a17c
Create Date: 2026-07-13 21:22:26.716003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69958028f74'
down_revision: Union[str, Sequence[str], None] = '388df832a17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE email_status ADD VALUE IF NOT EXISTS 'permanent_failure'")
    op.alter_column('certificates', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('certificates_event_id_fkey'), 'certificates', type_='foreignkey')
    op.drop_constraint(op.f('certificates_user_id_fkey'), 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificates', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('event_registrations_event_id_fkey'), 'event_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'event_registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('feedback', 'submitted_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('feedback_academic_resource_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_submitted_by_fkey'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_event_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'users', ['submitted_by'], ['id'], ondelete='SET NULL')
    op.drop_column('feedback', 'event_id')
    op.drop_column('feedback', 'academic_resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('academic_resource_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_event_id_fkey'), 'feedback', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('feedback_submitted_by_fkey'), 'feedback', 'users', ['submitted_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('feedback_academic_resource_id_fkey'), 'feedback', 'academic_resources', ['academic_resource_id'], ['id'], ondelete='CASCADE')
    op.alter_column('feedback', 'submitted_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('event_registrations_event_id_fkey'), 'event_registrations', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key(op.f('certificates_user_id_fkey'), 'certificates', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('certificates_event_id_fkey'), 'certificates', 'events', ['event_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('certificates', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
