"""add_hero_slides

Revision ID: ec3c66ef1a49
Revises: 5626195f3bd9
Create Date: 2026-07-16 21:59:15.631266

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec3c66ef1a49"
down_revision: str | Sequence[str] | None = "5626195f3bd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero_slides",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("heading", sa.String(length=200), nullable=False),
        sa.Column("highlight", sa.String(length=200), nullable=False),
        sa.Column("sub", sa.Text(), nullable=False),
        sa.Column("primary_button_label", sa.String(length=100), nullable=False),
        sa.Column("primary_button_path", sa.String(length=500), nullable=False),
        sa.Column("secondary_button_label", sa.String(length=100), nullable=False),
        sa.Column("secondary_button_path", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hero_slides")
    # ### end Alembic commands ###
